# Generated by Django 5.2.17 on 2026-09-14 06:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_cartitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'جديد'), ('processing', 'قيد التجهيز'), ('delivered', 'تم التسليم'), ('cancelled', 'ملغي')], default='new', max_length=20, verbose_name='حالة الطلب')),
                ('full_name', models.CharField(max_length=200, verbose_name='الاسم الكامل')),
                ('phone', models.CharField(max_length=30, verbose_name='رقم الهاتف')),
                ('address', models.TextField(verbose_name='العنوان')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('payment_method', models.CharField(choices=[('cash_on_delivery', 'الدفع عند الاستلام')], default='cash_on_delivery', max_length=30, verbose_name='طريقة الدفع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ إنشاء الطلب')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='العميل')),
            ],
            options={
                'verbose_name': 'طلب',
                'verbose_name_plural': 'الطلبات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='اسم المنتج وقت الطلب')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='سعر الوحدة وقت الطلب')),
                ('quantity', models.PositiveIntegerField(verbose_name='الكمية')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.order', verbose_name='الطلب')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='store.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'عنصر طلب',
                'verbose_name_plural': 'عناصر الطلب',
                'ordering': ['id'],
            },
        ),
    ]
