# Generated by Django 5.2.17 on 2026-09-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_customerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='الصورة الشخصية'),
        ),
    ]
