# Generated by Django 5.2.17 on 2026-09-21 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_customerprofile_profile_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'permissions': [('view_dashboard', 'Can view administration dashboard'), ('view_customer', 'Can view customer list')], 'verbose_name': 'منتج', 'verbose_name_plural': 'المنتجات'},
        ),
    ]
